// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5800ZiwtnWtxaYGNyZSAwSFtO28IV89g',
    appId: '1:740465389501:web:c0602345e40cb99577acd4',
    messagingSenderId: '740465389501',
    projectId: 'pancake-app-7698a',
    authDomain: 'pancake-app-7698a.firebaseapp.com',
    storageBucket: 'pancake-app-7698a.firebasestorage.app',
    measurementId: 'G-8SE84C6091',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqjioISAwsotiaxujHf3AeR22U1yW1al8',
    appId: '1:740465389501:android:09411104ba8c170d77acd4',
    messagingSenderId: '740465389501',
    projectId: 'pancake-app-7698a',
    storageBucket: 'pancake-app-7698a.firebasestorage.app',
  );
}
